pretrained_base_model_path: 'pretrained_weights/sd-image-variations-diffusers'
image_encoder_path: 'pretrained_weights/sd-image-variations-diffusers/image_encoder'
vae_path: 'pretrained_weights/stable-video-diffusion-img2vid-xt/vae'

denoising_unet_path: "pretrained_weights/xnemo_denoising_unet.pth"
temporal_module_path: "pretrained_weights/xnemo_temporal_module.pth"

inference_config: "configs/inference/inference_xnemo_stage2.yaml"
weight_dtype: 'fp16'

test_cases:
  'demo/ref_image.png':
  - 'demo/driving_video.mp4'
